<?xml version="1.0" encoding="UTF-8"?>

<!-- DTD-валидация -->
<!DOCTYPE Site[
<!ELEMENT Site (Mainpage, WeaponMainPage, ArmorMainPage, Contact, About, Footer)>

<!ATTLIST Site xmlns CDATA #FIXED ''>

<!ELEMENT Mainpage (Picture)+>
<!ATTLIST Mainpage
  xmlns CDATA #FIXED ''>

<!ELEMENT WeaponMainPage (SworsdMainPage,AxesMainPage,WoodenMainPage,
                          UniqueMainPage)>
<!ATTLIST WeaponMainPage
  xmlns CDATA #FIXED ''>

<!ELEMENT ArmorMainPage (EarlyChivarly,MiddleChivarly,LateChivarly)>
<!ATTLIST ArmorMainPage
  xmlns CDATA #FIXED ''>

<!ELEMENT Contact (text)>
<!ATTLIST Contact
  xmlns CDATA #FIXED ''>

<!ELEMENT About (text)+>
<!ATTLIST About
  xmlns CDATA #FIXED ''>

<!ELEMENT Footer (text)+>
<!ATTLIST Footer
  xmlns CDATA #FIXED ''>

<!ELEMENT SworsdMainPage (Longsword,Greatsword)>
<!ATTLIST SworsdMainPage
  xmlns CDATA #FIXED ''>

<!ELEMENT AxesMainPage EMPTY>
<!ATTLIST AxesMainPage
  xmlns CDATA #FIXED ''>

<!ELEMENT WoodenMainPage EMPTY>
<!ATTLIST WoodenMainPage
  xmlns CDATA #FIXED ''>

<!ELEMENT UniqueMainPage EMPTY>
<!ATTLIST UniqueMainPage
  xmlns CDATA #FIXED ''>

<!ELEMENT EarlyChivarly EMPTY>
<!ATTLIST EarlyChivarly
  xmlns CDATA #FIXED ''>

<!ELEMENT MiddleChivarly EMPTY>
<!ATTLIST MiddleChivarly
  xmlns CDATA #FIXED ''>

<!ELEMENT LateChivarly EMPTY>
<!ATTLIST LateChivarly
  xmlns CDATA #FIXED ''>

<!ELEMENT Longsword (Picture+,text+)>
<!ATTLIST Longsword
  xmlns CDATA #FIXED ''>

<!ELEMENT Greatsword (Picture+,text)>
<!ATTLIST Greatsword
  xmlns CDATA #FIXED ''>

<!ELEMENT Picture EMPTY>
<!ATTLIST Picture
  xmlns CDATA #FIXED ''
  border CDATA #REQUIRED
  path CDATA #REQUIRED>

<!ELEMENT text (#PCDATA)>
<!ATTLIST text xmlns CDATA #FIXED ''>
]>

<!-- База данных сайта -->
<Site>
    
    <!-- Каждый text соответствует одному абзацу -->
    
    <Mainpage>
        <Picture path = "" border = ""></Picture>
        <Picture path = "" border = ""></Picture>
    </Mainpage>
    
    <WeaponMainPage>
        
        <SworsdMainPage>

            <Longsword>
                <Picture path = "/DOJ745.github.io/Pictures/Weapon/Swords/Longsword1.jpg" border = "border"></Picture>
                <Picture path = "/DOJ745.github.io/Pictures/Weapon/Swords/Longsword2.png" border = "border"></Picture>
                <Picture path = "/DOJ745.github.io/Pictures/Weapon/Swords/Longsword3.jpg" border = "border"></Picture>
                <text>Термин «длинный меч» в историографии появляется впервые как перевод немецкого langes schwert. Этот термин используется в оружиеведении, а также часто встречается в германских фехтовальных трактатах XV и XVI веков, откуда, скорее всего, и ведёт своё происхождение. Стоит отметить, что этим понятием в фехтовальных трактатах обозначался не столько тип меча, сколько способ его применения. Длинный меч – это меч, удерживаемый двумя руками за рукоять и применяемый как для рубящих ударов, так и для уколов. Прямым аналогом немецкого langes schwert в синхронных итальянских источниках является spada da due mani. Сходство изображений этих мечей в фехтовальных трактатах, а также совпадение описываемых приёмов позволяют предположить, что германский термин langes schwert и итальянский spada da due mani в первой половине – третьей четверти XV столетия синонимичны.</text>
                <text>Один из первых трактатов, в котором описано применение меча двумя руками – это знаменитый «Цветок битвы» Фиоре ди Либери. Несколько списков этого манускрипта датируются 1404-1410 годами, а самый пространный из них посвящён патрону Фиоре, Никколо III д’Эсте, знаменитому кондотьеру, в то время обучавшемуся у ди Либери искусству боя. В них показан бой с длинным мечом в одной и двух руках, при этом одноручный хват применяется в основном для самообороны и не предполагает сложных приёмов, в то время как для хвата двумя руками разработана система позиций и перемещений; большое значение имеет дистанция, слабая и сильная доли своего меча и оружия противника. Можно предположить, что применение меча двумя руками уже во второй половине XIV века выделилось в особую фехтовальную технику.</text>
                <text>Также стоит учесть, что его первые образцы появились в начале XIII века, а уже более точная терминология появилась позднее. Такие мечи были весьма лёгкимим, порядка 1 кг. Длина лезвия составляла порядка 85 см, в то время как общая длина меча варьировалась от 105 до 130 см. Состоит же меч из привычных частей: гарда(она же эфес), обоюдноострое лезвие и рукоять, оснащённая навершием, которое было либо монолитным, либо его можно было открутить и кинуть во врага, дабы показать ему, кто здесь доминирует на поле брани.</text>
                <text>Мечом владеть могли далеко не все, ведь выковать клинок, который будет выдерживать удары об броню, при этом прорубая её, да ещё чтобы был хорошо сбалансирован... Скажем так, обывателю тех лет такой меч мог либо присниться, либо вонзиться в его тушку в ходе очередной междуусобицы от более богатого сословия. Но не в этом суть. Длинный меч был достаточно универсальным на то время оружием, ибо кожаные доспехи он прорубал с лёгкостью, кольчуга ему была не страшна, а рыцарь в латах уже считался достоиным опонентом. Как хорош бы меч не рубил, латы он порубит, если его перед боем будет затачивать специальная рота. А вот проколоть их можно, если повезёт. Зачастую при бое с такой жестянкой применяли обратный хват, так называемый "mordhau"(или техника "половины меча", как вам угодно): меч берётся за лезвие и боец наносит удары эфесом, либо весьма сильные уколы путём выполнения выпадов. Конечно, техника специфическая, однако она весьма неплохо помогала в раскрытии внутреннего мира вашего соперника. Зачастую старались бить по шлему, ведь контуженный боец не особо хочет драться, да и прилечь захочет от усталости, а там уже и до укола в шею при помощи карманного кинжала недалеко. Тем не менее это не значит, что ваш оппонент не подсмотрит за вами и не повторит ваше уникальное движение. Там уже начинается фехтование, парирования, выпады, лязгание меча о меч и прочие сладости настоящего мужского боя. Побеждает же тот, кто убил врага, как бы логично это не звучало</text>
                <text>В дальнейшем этот меч становился другим в сечении, укорачивался, удлиннялся и так до тех пор, пока не появился огнестрел. Там уже фехтование особой роли не играло, да и латы тоже</text>
            </Longsword>
            
            <Greatsword>
                <Picture path = "" border = ""></Picture>
                <Picture path = "" border = ""></Picture>
                <text></text>
            </Greatsword>
            
        </SworsdMainPage>
        
        <AxesMainPage>
        </AxesMainPage>
        
        <WoodenMainPage>
        </WoodenMainPage>
        
        <UniqueMainPage>
        </UniqueMainPage>
        
    </WeaponMainPage>
    
    <ArmorMainPage>
        
        <EarlyChivarly>
        </EarlyChivarly>
        
        <MiddleChivarly>
        </MiddleChivarly>
        
        <LateChivarly>
        </LateChivarly>
        
    </ArmorMainPage>
    
    <Contact>
        <text>Всё-таки не все контакты были заляпаны. Кажись, тут можно что-то различить. Действительно. Вот он, адрес создателя сие сайта. Так что все ваши вопросы пройдут через канцелярию, писаря и цензуру, а потом сюда, на andrey745fa@gmail.com. Коль не получилось доставить свой свиток туда, присылайте на andreyfa12@mail.ru. Наш гонец доставит ваше послание на самой быстрой кляче королевства</text>
    </Contact>
    
    <About>
        <text>Приветствую вас, гордые рыцари, простолюдины и просто проходящие мимо люди и нелюди! Вы попали на сайт, где можно узнать об многих видах оружия, и про доспехи тоже. Здесь вы найдёте(или нет) необходимую для вас информацию об занимательных вещах средних веков из самых свежих на то время свитков. Мечи, топоры, булавы, копья - всё это может вызывать как восхищение, так и страх, так и непонимание того, накой вы здесь. Но мы же с вами люди опытные, просто так в бадью с лошадиным навозом не лезем. Перед этим мы его нюхаем, а потом ныряем с головой.</text>
        <text>Про доспехи мы(я) тоже не забыли. Их, конечно, хватает, но наша команда в лице одного опытного, немножео уставшего и  немножко полысевшего от стресса человека решила грамотно распределить всевозможные виды боевых одеяний на три группы. Вы можете сказать, что периодизация должна быть точнее, ведь раннее средневековье звучит как-то расплывчато, можно было бы распределить по странам, по более точным временным промежуткам, ведь мы же люди придирчивые и любим порядок. Но на этом сайте всё как в средневековье: хаотично, непонятно, но очень интересно, и, возможно, немного набожно. Не волнуйтесь, нужный доспех вы найдёте, если он будет присутствовать на сайте. Хотя одному из своих оруженосцев я недроверяю: в прошлый раз наши гордые писари недосчитали одного бацинета...</text>
        <text>А теперь прогуливайтесь по закоулкам сие сайта и не мешайте нашим упорным трудягам и работягам доделать это чудо до конца.Заодно я подниму им настроение тем, что они это делают во славу нашего Бога! А потом золотым крестом по лбу дам, я же добрый.</text>
    </About>
    
    <Footer>
        <text>Министерство образования РБ "Белорусский государственный технологический университет"</text>
        <text>Контакты были утеряны гонцом в ходе неравной погони против 30 тевтонцев где-то в Литве</text>
        <text>Авторские права были загажены чернильной плямбой в Полоцке</text>
    </Footer>
    
</Site>